In [3]:
#importing numpy library
import numpy as np

#checking its version
np.__version__


'2.0.1'

In [6]:
#creating numpy array
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [7]:
lst=[10,15,45,80,55]
arr=np.array(lst)
arr

array([10, 15, 45, 80, 55])

In [13]:
#checking type of array
type(arr)

#numpy = numerical python
#85% of the code of numpy is written in C language and rest is written in python
#ndarray = n-dimensional array

numpy.ndarray

In [11]:
#checking dimension of the array (1D array)
arr.ndim

1

In [14]:
#checking array size
arr.size        #number of items in the array

5

In [15]:
len(arr)
#number of items in the array using len()

5

In [16]:
arr.shape
#number of items in the array

(5,)

In [19]:
arr.dtype
#data type

dtype('int64')

In [20]:
arr

array([10, 15, 45, 80, 55])

In [21]:
arr=np.array([10,20,30,40,50])
arr    
#all int values

array([10, 20, 30, 40, 50])

In [22]:
arr=np.array([10,20,30,40,50,25.2])
arr

array([10. , 20. , 30. , 40. , 50. , 25.2])

In [24]:
arr.dtype

#because of 25.2, type of array became float
#numpy array is homogeneous

dtype('float64')

In [25]:
arr=np.array([10,20,30,40,50,'Hello'])
arr

array(['10', '20', '30', '40', '50', 'Hello'], dtype='<U21')

In [26]:
arr.dtype

dtype('<U21')

In [27]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [29]:
a[0]

#indexing is allowed 
#(same as list, both positive and negative indexing)

np.int64(10)

In [31]:
a[-1:-4]  #step is 1, that's why empty array

array([], dtype=int64)

In [32]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [34]:
arr[4:]    #slicing is possible in numpy arrays

array([40, 50, 60])

In [35]:
arr[-3:]

array([40, 50, 60])

In [36]:
arr[-1:-4:-1]

array([60, 50, 40])

In [37]:
arr[-3::-1]

array([40, 30, 20, 10, 25])

In [39]:
#creating a new numpy array

a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [43]:
#if we perform any operation, then it is performed on each and every element
a+5

#each value is incremented by 5

array([15, 25, 35, 45, 55])

In [44]:
a
#but no changes has been done in the original array 'a'

array([10, 20, 30, 40, 50])

In [45]:
a*10

array([100, 200, 300, 400, 500])

In [46]:
a

array([10, 20, 30, 40, 50])

In [48]:
min(a)
#it will show the minimum value from the array 'a'

np.int64(10)

In [49]:
max(a)
#it will show the maximum value from the array 'a'

np.int64(50)

In [50]:
sum(a)
#it will add all the elements in the array

np.int64(150)

In [56]:
a=np.array([5,9,10,34,67,98,2])
a

array([ 5,  9, 10, 34, 67, 98,  2])

In [57]:
#mean=average
np.mean(a)

#data type of that mean value is float

np.float64(32.142857142857146)

In [59]:
#median = middle most element
np.median(a)

np.float64(10.0)

In [60]:
np.mode(a)

AttributeError: module 'numpy' has no attribute 'mode'

In [10]:
import numpy as np
np.random.randint(1,5)

#generating random int value using numpy
#select any one value between 1 to 5 (5 is included)

3

In [14]:
np.random.randint(1,5)

4

In [15]:
##NOW, importing random module
#and generating random values using this module

import random
random.randint(1,5)

1

In [17]:
random.randint(1,5)

4

In [18]:
random.randint(1,5)

3

In [29]:
arr=np.random.randint(1,200,100)

# it means that it will generate 100 random integer values 
#which are all between 1 to 200...

arr

array([ 66, 110, 121, 186,  45,  56, 114, 137,  55, 111,  68,   9,  16,
       157,  81, 148,  42,  44, 146, 119,  34,  68,  32, 148,  75, 136,
        85,  58,  96, 143,  39, 161,  79, 126,  44,  78,  78,  41, 167,
        50, 189,  51, 113, 153,  60, 162,  11,  21,  77, 114, 163, 128,
       100,  56,  27, 143, 127, 109, 176,  11,  95, 113, 180, 164,  52,
        88, 107,  93, 188,  52,  68,  91, 113,  42, 186,   9, 170, 180,
        82, 150, 125,  23, 129,  37,  31,  16,  22,  70,  41,  45,  59,
       140, 165,  89, 163,  20, 163,   7,  67, 163], dtype=int32)

In [30]:
type(arr)

numpy.ndarray

In [31]:
arr.dtype    
#By default dtype of arr will be 'int32'

dtype('int32')

In [32]:
#But let's say we want dtype='int64' then we need to pass a parameter....

arr=np.random.randint(1,200,100,dtype='int64')
arr

array([  9, 160,  22,  39, 170,   3, 110,  49, 191, 198,  38, 141,  72,
       100, 181,  69,  32,   4, 167, 167, 153,  46, 170, 103,  52, 166,
        14, 194,  61, 125, 112,  26, 182,   6, 194, 177,  42, 124, 176,
       142, 163, 149,  68, 121, 145,  41,  12, 130, 150,  18, 188, 114,
        89, 180,  69, 137,  33, 163,  80, 178,  21, 134, 171,  51,  88,
       143, 197,  40,  36, 138, 140, 196, 157, 182,  56, 161,  94,  90,
       108,   7,  20,  74,  35,  79,  85, 128, 190, 144,  20,  63, 160,
        27,  36,  68,  33, 170, 180, 155, 154,   7])

In [33]:
type(arr)

numpy.ndarray

In [34]:
arr.dtype
#Now, its dtype will be 'int64'

dtype('int64')

In [35]:
arr

array([  9, 160,  22,  39, 170,   3, 110,  49, 191, 198,  38, 141,  72,
       100, 181,  69,  32,   4, 167, 167, 153,  46, 170, 103,  52, 166,
        14, 194,  61, 125, 112,  26, 182,   6, 194, 177,  42, 124, 176,
       142, 163, 149,  68, 121, 145,  41,  12, 130, 150,  18, 188, 114,
        89, 180,  69, 137,  33, 163,  80, 178,  21, 134, 171,  51,  88,
       143, 197,  40,  36, 138, 140, 196, 157, 182,  56, 161,  94,  90,
       108,   7,  20,  74,  35,  79,  85, 128, 190, 144,  20,  63, 160,
        27,  36,  68,  33, 170, 180, 155, 154,   7])

In [37]:
## Filter all those items that are less than 100
arr<100

array([ True, False,  True,  True, False,  True, False,  True, False,
       False,  True, False,  True, False, False,  True,  True,  True,
       False, False, False,  True, False, False,  True, False,  True,
       False,  True, False, False,  True, False,  True, False, False,
        True, False, False, False, False, False,  True, False, False,
        True,  True, False, False,  True, False, False,  True, False,
        True, False,  True, False,  True, False,  True, False, False,
        True,  True, False, False,  True,  True, False, False, False,
       False, False,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True, False, False, False,  True,  True,
       False,  True,  True,  True,  True, False, False, False, False,
        True])

In [45]:
#to filter out the values which are less than 100

arr[arr<100]

array([ 9, 22, 39,  3, 49, 38, 72, 69, 32,  4, 46, 52, 14, 61, 26,  6, 42,
       68, 41, 12, 18, 89, 69, 33, 80, 21, 51, 88, 40, 36, 56, 94, 90,  7,
       20, 74, 35, 79, 85, 20, 63, 27, 36, 68, 33,  7])

In [46]:
sum(arr<100)

np.int64(46)

In [48]:
len(arr[arr<100])  #using len()

#46 items are there that are less than 100

46

In [49]:
#     2D array

In [50]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [51]:
type(lst)

list

In [52]:
arr=np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
type(arr)

numpy.ndarray

In [55]:
arr.ndim
#number of dimensions - 2

2

In [56]:
arr.shape

#3*3 matrix
#3 rows and 3 columns

(3, 3)

In [57]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
#indexing
arr[0]     #row

array([1, 2, 3])

In [59]:
arr[2]

array([7, 8, 9])

In [61]:
#slicing
arr[0:2]    # 2 is not included

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
#slicing using negative indexing
arr[-1]

array([7, 8, 9])

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr[1:3,1:3]

#or arr[1:,1:]
#Before comma, it represents rows
#And after comma, it represents columns

# arr[rows, columns]

array([[5, 6],
       [8, 9]])

In [68]:
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [69]:
arr[1:,0:2]

array([[4, 5],
       [7, 8]])

In [70]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
#Using negative slicing

arr[-2:]
# or     arr[-2:,-3:]

array([[4, 5, 6],
       [7, 8, 9]])

In [84]:
arr[-2]

array([4, 5, 6])

In [85]:
arr[-2:-4:-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [75]:
arr[-1:-3:-1]

array([[7, 8, 9],
       [4, 5, 6]])

In [76]:
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [77]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr[-2:,-2:]

array([[5, 6],
       [8, 9]])

In [89]:
arr[-3:-1,-3:-1]    #step is 1

array([[1, 2],
       [4, 5]])

In [90]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
a=np.ones(10)
a

#it will give us an array of 10 elements with
#the value 1 but by default it will be floating numbers' array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [141]:
type(a[0])

numpy.float64

In [143]:
np.ones    #arguments of the function ones()

<function numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)>

In [144]:
np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'

In [146]:
np.ones(3,3)

TypeError: Cannot interpret '3' as a data type

In [24]:
a=np.ones(5,'int')
a
#array of 5 elements with the value 1 of int data type

array([1, 1, 1, 1, 1])

In [25]:
type(a)

numpy.ndarray

In [156]:
type(a[0])

numpy.int64

In [2]:
import numpy as np

In [6]:
a = np.zeros(10)
a

#it will give us an array of 10 elements with
#the value 0 but by default it will be floating numbers' array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
type(a)

numpy.ndarray

In [8]:
type(a[0])

numpy.float64

In [21]:
a = np.zeros(5,'int')    
a

array([0, 0, 0, 0, 0])

In [22]:
type(a[0])     #now dtype will be int

numpy.int32

In [53]:
np.linspace(1,50,10)     

#it will generate 10 evenly spaced elements between 1 to 50

#The NumPy.linspace() function returns an array of evenly spaced float values within the specified interval [start, stop].
#It is similar to NumPy.arange() function but instead of a step, it uses a sample number. 

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [36]:
np.arange(1,5)

#The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. 

array([1, 2, 3, 4])

In [40]:
np.arange(1,11,2,dtype=float)     #dtype = float    

array([1., 3., 5., 7., 9.])

In [41]:
##  3D array

In [42]:
lst = [[[1, 2, 3],[4, 5, 6],[7, 8, 9]],
       [[1, 2, 3],[4, 5, 6],[7, 8, 9]],
       [[1, 2, 3],[4, 5, 6],[7, 8, 9]],
       [[1, 2, 3],[4, 5, 6],[7, 8, 9]]]
lst

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [43]:
type(lst)

list

In [44]:
a = np.array(lst)
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [48]:
a.shape

# here 4 represents table
# 3 represents rows
# and 3 represents columns

(4, 3, 3)

In [47]:
a.ndim

#number of dimensions - 3 because it is a 3D array

3

In [51]:
a.size    

# there are total 36 elements inside the whole array
# a.shape = (4,3,3)
# so, if we do 4*3*3 we will get 36   (4*3*3 = 36)

36

In [52]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [54]:
a[0]

#indexing

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a[-1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
#slicing

a[0:,1:,1:]

# a[table, rows, columns]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [59]:
arr=a.ravel()
arr

#The numpy.ravel() functions returns contiguous flattened array
#(1D array with all the input-array elements and with the same type as it).

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
type(arr)

numpy.ndarray

In [63]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [65]:
# flatten() function returns a copy of the array collapsed into one dimension.

a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# reshape() function shapes an array without changing the data of the array.

a.reshape(36,)

# we passed 36 as an argument because in the array 'a', its shape is (4,3,3) that is total elements is 4*3*3 = 36
# so it will reshape the 3D array 'a' into 1-D array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr = np.arange(1,9)
arr.reshape(2,4)

# reshape(2,4)
# 2 stands for rows
# 3 stands for columns
# so it will be reshaped into a 2*4 matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
# argmax() function returns indices of the max element of the array in a particular axis. 

# Syntax   ------->    numpy.argmax(array, axis = None, out = None)
# axis = 0, here 0 represents rows
# axis = 1, here 0 represents columns

# If No axis mentioned, so works on entire array

In [76]:
lst=[5,2,8,6,1,9]
arr = np.array(lst)
arr

array([5, 2, 8, 6, 1, 9])

In [79]:
arr.argmax()     # element on index 5 is max

5

In [80]:
arr.argmin()    # element in index 4 is min

4

In [92]:
lst=[5,2,8,6,1,9,3,7,4]
arr2 = np.array(lst)
arr2 = arr2.reshape(3,3)
arr2

array([[5, 2, 8],
       [6, 1, 9],
       [3, 7, 4]])

In [93]:
arr2

array([[5, 2, 8],
       [6, 1, 9],
       [3, 7, 4]])

In [94]:
arr2.argmax(axis=0)

array([1, 2, 1], dtype=int64)

In [95]:
arr2.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [97]:
# if there is any confusion on axes
# then we can learn from

#  https://www.sharpsightlabs.com/blog/numpy-axes-explained/#:~:text=In%20a%20NumPy%20array%2C%20axis,runs%20downward%20down%20the%20rows.

In [101]:
arr2.argmin(axis=0)

array([2, 1, 2], dtype=int64)

In [100]:
arr2.argmin(axis=1)

array([1, 1, 0], dtype=int64)

In [1]:
# argsort() function is used to perform an indirect sort along the given axis using the algorithm specified by the kind keyword. 
# It returns an array of indices of the same shape as 'arr' that would sort the array. It means indices of value arranged in ascending order

# Syntax : numpy.argsort(arr, axis=-1, kind=’quicksort’, order=None) 

In [2]:
import numpy as np
arr = np.array([12,45,8,1,50,20])
arr

array([12, 45,  8,  1, 50, 20])

In [6]:
arr.argsort()     

# or np.argsort(arr)     

array([3, 2, 0, 5, 1, 4], dtype=int64)

In [9]:
lst = [12,45,8,1,50,20]
arr = np.array(lst)
arr = arr.reshape(2,3)
arr

array([[12, 45,  8],
       [ 1, 50, 20]])

In [12]:
arr.argsort(axis=0)       #according to rows

array([[1, 0, 0],
       [0, 1, 1]], dtype=int64)

In [13]:
arr.argsort(axis=1)       #according to columns

array([[2, 0, 1],
       [0, 2, 1]], dtype=int64)

In [14]:
# The numpy.amax() method returns the maximum of an array or maximum along the axis(if mentioned).
# Syntax
#       numpy.amax(arr, axis = None, out = None, keepdims = <class numpy._globals._NoValue>)

# axis : [int or tuples of int] axis along which we want the max value. Otherwise, it will consider arr to be flattened.

In [15]:
lst = [12,45,8,1,50,20]
arr = np.array(lst)
arr

array([12, 45,  8,  1, 50, 20])

In [17]:
np.amax(arr)

50

In [19]:
lst = [12,45,8,1,50,20]
arr = np.array(lst)
arr = arr.reshape(2,3)
arr     

#now arr is a 2D array

array([[12, 45,  8],
       [ 1, 50, 20]])

In [21]:
np.amax(arr)
# if we do not give any axis, by default it will consider arr to be flattened.

50

In [23]:
np.amax(arr,axis=0)

array([12, 50, 20])

In [24]:
np.amax(arr,axis=1)

array([45, 50])

In [25]:
# numpy.amin() function returns minimum of an array or minimum along axis(if mentioned). 
# Syntax : 
#       numpy.amin(arr, axis = None, out = None, keepdims = <class numpy._globals._NoValue>)

# axis : [int or tuples of int]axis along which we want the min value. Otherwise, it will consider arr to be flattened.

#similar to amax function, but this calculates min....

In [26]:
lst = [12,45,8,1,50,20]
arr = np.array(lst)
arr

array([12, 45,  8,  1, 50, 20])

In [27]:
np.amin(arr)

1

In [28]:
lst = [12,45,8,1,50,20]
arr = np.array(lst)
arr = arr.reshape(2,3)
arr     

#now arr is a 2D array

array([[12, 45,  8],
       [ 1, 50, 20]])

In [30]:
np.amin(arr,axis=0)

array([ 1, 45,  8])

In [31]:
np.amin(arr,axis=1)

array([8, 1])

In [44]:
# sort function
# sort function sorts the array and then update the changes made into the original array
# so, the original array gets sorted

In [33]:
arr = np.array([12,45,8,1,50,20])
arr

array([12, 45,  8,  1, 50, 20])

In [37]:
arr.sort()
arr         
# original array'arr' has been sorted

array([ 1,  8, 12, 20, 45, 50])

In [38]:
lst = [12,45,8,1,50,20]
arr = np.array(lst)
arr = arr.reshape(2,3)
arr     

array([[12, 45,  8],
       [ 1, 50, 20]])

In [39]:
arr.sort(axis=0)

In [40]:
arr

array([[ 1, 45,  8],
       [12, 50, 20]])

In [41]:
arr.sort(axis=1)

In [42]:
arr

array([[ 1,  8, 45],
       [12, 20, 50]])

In [47]:
lst = [12,45,8,1,50,20]
arr = np.array(lst)
arr = arr.reshape(2,3)
arr

array([[12, 45,  8],
       [ 1, 50, 20]])

In [52]:
arr.sort()
arr

# with no axes passes

array([[ 8, 12, 45],
       [ 1, 20, 50]])

In [72]:
# numpy.full(shape, fill_value, dtype = None, order = ‘C’): Return a new array with the same shape and type as a given array filled with a fill_value.
# Parameters :
    # shape      : Number of rows
    # order      : C_contiguous or F_contiguous
    # dtype      : [optional, float(by Default)] Data type of returned array.  
    # fill_value : [bool, optional] Value to fill in the array.
# Returns    :
    #   ndarray

In [56]:
a=np.full((2,3),10)
a

array([[10, 10, 10],
       [10, 10, 10]])

In [57]:
type(a)

numpy.ndarray

In [58]:
type(a[0][0])

numpy.int32

In [60]:
a=np.full([3, 3], 10.1)
a

array([[10.1, 10.1, 10.1],
       [10.1, 10.1, 10.1],
       [10.1, 10.1, 10.1]])

In [61]:
type(a[0][0])

numpy.float64

In [69]:
np.full(3,10,dtype=float)

array([10., 10., 10.])

In [73]:
# numpy.identity(n, dtype = None) : Return a identity matrix i.e. a square matrix with ones on the main diagonal.
# Parameters : 
    # n     : [int] Dimension n x n of output array  
    # dtype : [optional, float(by Default)] Data type of returned array.  
# Returns : 
    # identity array of dimension n x n,  with its main diagonal set to one, and all other elements 0.

In [74]:
np.identity(3)

#dtype is float, by default

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
np.identity(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [87]:
# numpy.count_nonzero() function counts the number of non-zero values in the array arr.

#Syntax : numpy.count_nonzero(arr, axis=None)

#Parameters :
   #arr : [array_like] The array for which to count non-zeros.
   #axis : [int or tuple, optional] Axis or tuple of axes along which to count non-zeros. Default is None, meaning that non-zeros will be counted along a flattened version of arr.

#Return : 
   #[int or array of int] Number of non-zero values in the array along a given axis. Otherwise, the total number of non-zero values in the array is returned.

In [88]:
arr = np.array([10,3,0,-1,0,6])
arr

array([10,  3,  0, -1,  0,  6])

In [89]:
np.count_nonzero(arr)

4

In [90]:
lst = [[10,3,0],
       [0,4,-2],
       [6,8,9]]
arr = np.array(lst)
arr

array([[10,  3,  0],
       [ 0,  4, -2],
       [ 6,  8,  9]])

In [92]:
np.count_nonzero(arr)

7

In [93]:
np.count_nonzero(arr,axis=0)

array([2, 3, 2], dtype=int64)

In [95]:
np.count_nonzero(arr,axis=1)

array([2, 2, 3], dtype=int64)

In [99]:
#numpy.argwhere() function is used to find the indices of array elements that are non-zero, grouped by element.

#Syntax : numpy.argwhere(arr)
#Parameters :
   #arr : [array_like] Input array.
#Return : 
   #[ndarray] Indices of elements that are non-zero. Indices are grouped by element.

In [97]:
arr = np.array([2,4,0,-2,8,0])
arr

array([ 2,  4,  0, -2,  8,  0])

In [98]:
np.argwhere(arr)

array([[0],
       [1],
       [3],
       [4]], dtype=int64)

In [101]:
# 2D array

lst = [[10,3,0],
       [0,4,-2],
       [6,8,9]]
arr = np.array(lst)
arr

array([[10,  3,  0],
       [ 0,  4, -2],
       [ 6,  8,  9]])

In [102]:
np.argwhere(arr)

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]], dtype=int64)

In [104]:
np.argwhere(arr>6)

# (arr>6) means that "Output indices greater than 6"

array([[0, 0],
       [2, 1],
       [2, 2]], dtype=int64)

In [117]:
# numpy.absolute(arr, out = None, ufunc ‘absolute’) : 
# or numpy.abs()

# This mathematical function helps user to calculate absolute value of each element. 

# For complex input, a + ib, the absolute value is \sqrt { a^2 + b^2 }. 
# Parameters :
   #arr  : [array_like] Input array or object whose elements, we need to test.
#Return :
   #An array with absolute value of each array.

In [116]:
lst = [1, -3, 15, -466] 
np.abs(lst)

array([  1,   3,  15, 466])

In [111]:
lst = [[-10,3,-8],
       [-5,4,-2],
       [-6,-8,9]]
arr = np.array(lst)
arr

array([[-10,   3,  -8],
       [ -5,   4,  -2],
       [ -6,  -8,   9]])

In [112]:
np.absolute(arr)

array([[10,  3,  8],
       [ 5,  4,  2],
       [ 6,  8,  9]])

In [119]:
# absolute function working on complex numbers

a = 4 + 3j
np.abs(a)

# or we can write np.absolute(a)

# ((4)^2 + (3)^2)   whole sqrt
# 16 + 9 = 25
# 25 whole sqrt = 5.0

5.0

In [128]:
# hstack()
# numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

arr1 = np.array([10,20,30,100])
arr2 = np.array([40,50,60])

#Stacking the 2 arrays horizontally
np.hstack((arr1,arr2))

array([ 10,  20,  30, 100,  40,  50,  60])

In [139]:
# hstack in 2D array

import numpy as np

# input array 
in_arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print ("2nd Input array : \n", in_arr2) 

# Stacking the two arrays horizontally 
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output stacked array :\n ", out_arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [142]:
# vstack()
# numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.

arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

#Stacking the 2 arrays horizontally
np.vstack((arr1,arr2))

array([[10, 20, 30],
       [40, 50, 60]])

In [143]:
#vstack in 2D array

import numpy as np 
  
# input array 
in_arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays vertically 
out_arr = np.vstack((in_arr1, in_arr2)) 
print ("Output stacked array :\n ", out_arr) 

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]


In [145]:
# where()
# np.where() function is used to return the indices of elements in an input array where the given condition is true. 

In [148]:
arr = np.array([1,2,3,4,5])
np.where(arr>3)

# np.where is used to find the indices of elements that are greater than 3 in the array ‘arr’. 

(array([3, 4], dtype=int64),)

In [150]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [151]:
np.where(arr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [152]:
# In the above example, we created a two-dimensional array ‘arr’. 
# We then used np.where to find the indices of elements in ‘arr’ that are greater than 5. 
# The function returns a tuple of arrays, each array representing the indices along a dimension of ‘arr’. 

# The first array in the tuple represents the row indices, and the second array represents the column indices. 
# So, the elements at positions (1,2), (2,0), (2,1), and (2,2) in ‘arr’ are greater than 5.

In [155]:

arr = np.array([1, 2, 3, 4, 5])
np.where(arr > 3, 'Greater than 3', 'Not greater than 3')


array(['Not greater than 3', 'Not greater than 3', 'Not greater than 3',
       'Greater than 3', 'Greater than 3'], dtype='<U18')

In [154]:
# In the above example, 
# np.where is used with 3 arguments: condition, value to use for elements where the condition is true, and value to use for elements where the condition is false. 
# The result is a new array where each element is either ‘Greater than 3’ or ‘Not greater than 3’ depending on whether the corresponding element in ‘arr’ is greater than 3. 
# This is particularly useful when we want to categorize or label data based on certain conditions.